#** Profile and context **
server.servlet.context-path = /WsSongList

#** Auth **
spring.jwt.timeout = 60
spring.jwt.user = WsSongListUser
spring.jwt.password = %BFA5u#zR%qVm7qJreBYb5$nobueNtnP
spring.jwt.key = xbswHx4c$9PC675Xwi2ePVn!R65vxXg9kLpxgHbj86bwJ2dAdt^&dw5vuram&XKn

# *** Encryption ***
spring.encryption.secret-key = rn^%HUfRRPksbHjG2Z482!isvuT^Q$9v

# *** Configuración H2 ***
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:songlist
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# *** Crear / actualizar tablas automáticamente ***
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# *** Consola web H2 ***
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console

# *** API Spotify ***
spotify.api-authentication.url=https://accounts.spotify.com/api/token
spotify.api-authentication.client-id=18a566c49a2e47dd9576b42f692766db
spotify.api-authentication.client-secret=daaabc27326e4415b466e084bf365685