#** Profile and context **
server.servlet.context-path = /WsSongList

#** Auth **
spring.jwt.timeout = 60
spring.jwt.user = WsSongListUser
spring.jwt.password = %BFA5u#zR%qVm7qJreBYb5$nobueNtnP
spring.jwt.key = xbswHx4c$9PC675Xwi2ePVn!R65vxXg9kLpxgHbj86bwJ2dAdt^&dw5vuram&XKn

# *** Encryption ***
spring.encryption.secret-key = rn^%HUfRRPksbHjG2Z482!isvuT^Q$9v
